### ISSUE TITLE
Old legacy context api used

### ISSUE THREAD

**Issue by ChetSocio** [ChetSocio/easy-reveal#1]
@willnguyen1312 take a look at revealbase.js file thats giving an error 

The error is as :
![received_361973683032076.png](https://github.com/ChetSocio/easy-reveal/assets/114129405/3823f787-f55b-4a6d-b932-3858b7b50bb6)

**Comment by willnguyen1312** [comment]
@ChetSocio It's just a warning, not breaking error 😅
